package org.example;

public enum Faculties {
    FACULTY_OF_MATHEMATICS_AND_COMPUTER_SCIENCE,
    FACULTY_OF_ECONOMIC_SCIENCES,
    FACULTY_OF_HISTORY_AND_PHILOSOPHY,
    FACULTY_OF_PHILOLOGY,
    FACULTY_OF_BIOLOGY_AND_SOIL_SCIENCE,
    FACULTY_OF_LAW
}